# Generated by Django 5.0.6 on 2024-05-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_roles_business_client_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='type',
            new_name='user_role',
        ),
        migrations.AlterModelTable(
            name='roles',
            table='roles',
        ),
    ]
